### ISSUE TITLE
Copy Example

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/Heiko-LOGIST#10]
https://github.com/T-systemsYoungsters/Heiko-LOGIST/blob/d1e21f11d80cb5e2e90864072ef70315f15b2d77/Aufgaben/python/5/lab.py#L31

its okay to copy the example and use it
but at least change some stuff so it doenst seems like it's only copy and paste
i know you did other stuff but you still keep stuff from the example which its completly unnecessary for your code

**Comment by heiko178** [comment]
Sorry, I haven't changed the copy stuff on my older files as of now.
