### ISSUE TITLE
unnecessary code

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/Heiko-LOGIST#25]
https://github.com/T-systemsYoungsters/Heiko-LOGIST/blob/886ee3157ba37a7aafd5a90b9b63f5b588efc364/Aufgaben/python/7/Worksheet07.md?plain=1#L74-L85

in Line 80 and Line 93 there is something unecessary

**Comment by heiko178** [comment]
only avg=0?

**Comment by phtrong** [comment]
think about line 80

**Comment by heiko178** [comment]
I can't find what you mean.

**Comment by phtrong** [comment]
is len() in line 80 necessary ?

**Comment by heiko178** [comment]
Yes, without it, the code doesn't work.

**Comment by phtrong** [comment]
yeah sorry my bad your answer ist completly correct this way

i just wanted that you get to this solution which make the code cleaner and simpler 

```python
my_list=[4,7,4,68,24,8,12,2] 
print(my_list) 
list_total=0 
  
for i in my_list: 
     list_total+=i
print(list_total) 
avg=0 
avg=list_total/len(my_list) 
print("The avarage is:",avg) 
```

this should work
