### ISSUE TITLE
Missing Task 15

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/Heiko-LOGIST#7]
https://github.com/T-systemsYoungsters/Heiko-LOGIST/blob/582037d21a406d1d5ec919f1fc181be48667d665/Aufgaben/python/7/Worksheet07.md?plain=1#L70

[Task 15](http://programarcadegames.com/worksheets/show_file.php?file=worksheet_07.php&lang=de)

**Comment by heiko178** [comment]
done
