### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/Heiko-LOGIST#8]
https://github.com/T-systemsYoungsters/Heiko-LOGIST/blob/582037d21a406d1d5ec919f1fc181be48667d665/Aufgaben/python/6/Worksheet06.md?plain=1#L13

Blast off isnt gonna print out.
But why?
[Link to the Worksheet 6](http://programarcadegames.com/worksheets/show_file.php?file=worksheet_06.php)

**Comment by heiko178** [comment]
I tested it and for me it works.

**Comment by phtrong** [comment]
![Screenshot 2022-02-23 135053](https://user-images.githubusercontent.com/58851170/155322966-c0a88e58-03c8-4067-8337-a60f078a7a51.png)

please think about it again
